/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/0/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API-токены текущего пользователя (ADR-0017, без секретов) */
        get: operations["SwatterWeb.ApiTokenController.index"];
        put?: never;
        /** Создать API-токен (плейнтекст возвращается один раз) */
        post: operations["SwatterWeb.ApiTokenController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Отозвать API-токен */
        delete: operations["SwatterWeb.ApiTokenController.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по email и паролю (устанавливает сессионный cookie) */
        post: operations["SwatterWeb.AuthController.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход (ревокация сессионного токена) */
        post: operations["SwatterWeb.AuthController.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь и его организации */
        get: operations["SwatterWeb.AuthController.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Нужен ли первый запуск (в системе нет пользователей) */
        get: operations["SwatterWeb.AuthController.setup_status"];
        put?: never;
        /** Первый запуск: создать owner-пользователя и организацию */
        post: operations["SwatterWeb.AuthController.setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/issues/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Деталка issue */
        get: operations["SwatterWeb.IssueController.show"];
        /** Смена статуса (resolve / ignore / unresolve) */
        put: operations["SwatterWeb.IssueController.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/issues/{issue_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить AI-анализ issue (ADR-0016, только по запросу)
         * @description Ставит фоновую джобу анализа на z.ai; результат опрашивается через деталку issue.
         */
        post: operations["SwatterWeb.IssueController.analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/issues/{issue_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** События issue (новые сверху) */
        get: operations["SwatterWeb.EventController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/issues/{issue_id}/events/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последнее событие issue (для деталки со стектрейсом) */
        get: operations["SwatterWeb.EventController.latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Организации текущего пользователя */
        get: operations["SwatterWeb.OrganizationController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/organizations/{org_slug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проекты организации (с DSN и счётчиками) */
        get: operations["SwatterWeb.ProjectController.index"];
        put?: never;
        /** Создать проект (сразу с DSN-ключом) */
        post: operations["SwatterWeb.ProjectController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/organizations/{org_slug}/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Спаны трейса по организации (кросс-проектно, ADR-0014) */
        get: operations["SwatterWeb.PerformanceController.trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/organizations/{org_slug}/traces/{trace_id}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ошибки трейса по организации (кросс-сервисная связка, ADR-0014) */
        get: operations["SwatterWeb.PerformanceController.trace_errors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Переименовать проект (slug неизменяем) */
        put: operations["SwatterWeb.ProjectController.update"];
        post?: never;
        /** Удалить проект со всеми данными (issues, события, релизы, DSN) */
        delete: operations["SwatterWeb.ProjectController.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/alert-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройки Telegram-алертов проекта (ADR-0013) */
        get: operations["SwatterWeb.AlertSettingsController.show"];
        /**
         * Обновить настройки алертов проекта
         * @description Частичное обновление: применяются только присланные поля.
         */
        put: operations["SwatterWeb.AlertSettingsController.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузка sourcemap-артефакта (multipart, ADR-0012)
         * @description Поля формы: `file` (файл), `debug_id`, `type` (source_map |
         *     minified_source), опц. `name`. Идемпотентно по (project, debug_id,
         *     type) — повтор заменяет.
         */
        post: operations["SwatterWeb.ArtifactController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Доступные значения фильтров проекта (environment/release) */
        get: operations["SwatterWeb.IssueController.filters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issues проекта
         * @description Сортировки: date (last_seen), new (first_seen), freq (times_seen).
         */
        get: operations["SwatterWeb.IssueController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/performance/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последние трейсы транзакции (корневые сегменты) */
        get: operations["SwatterWeb.PerformanceController.traces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/performance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Агрегаты по транзакциям проекта (ADR-0014, на лету из CH) */
        get: operations["SwatterWeb.PerformanceController.transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Релизы проекта (новые сверху) со счётчиком новых issues */
        get: operations["SwatterWeb.ReleaseController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/0/projects/{org_slug}/{project_slug}/releases/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Релиз и issues, впервые появившиеся в нём */
        get: operations["SwatterWeb.ReleaseController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * TransactionStat
         * @description Агрегат по транзакции за окно (ADR-0014)
         */
        TransactionStat: {
            count: number;
            /** Format: date-time */
            lastSeen: string;
            /** @description медиана длительности, мс */
            p50: number;
            /** @description 95-й перцентиль длительности, мс */
            p95: number;
            /** @description запросов в минуту за окно */
            rpm: number;
            transaction: string;
        };
        /** ApiTokenList */
        ApiTokenList: components["schemas"]["ApiToken"][];
        /** Artifact */
        Artifact: {
            debugId: string;
            id: string;
            name?: string | null;
            /** @description размер распакованного контента */
            size: number;
            /** @enum {string} */
            type: "source_map" | "minified_source";
        };
        /** RelatedErrorList */
        RelatedErrorList: components["schemas"]["RelatedError"][];
        /** Error */
        Error: {
            detail: string;
        };
        /** TraceSpan */
        TraceSpan: {
            description?: string;
            durationMs: number;
            /** Format: date-time */
            endTs: string;
            isSegment: boolean;
            op: string;
            parentSpanId: string;
            projectId?: string;
            projectSlug?: string | null;
            spanId: string;
            /** Format: date-time */
            startTs: string;
            status?: string;
            transaction?: string;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            name: string;
            platform?: string | null;
            slug: string;
        };
        /** CurrentUser */
        CurrentUser: {
            email: string;
            id: string;
            memberships: {
                organization: components["schemas"]["Organization"];
                /** @enum {string} */
                role: "owner" | "admin" | "member";
            }[];
            name?: string;
        };
        /**
         * AIAnalysis
         * @description AI-анализ issue (ADR-0016), запускается по запросу
         */
        AIAnalysis: {
            /** Format: date-time */
            analyzedAt?: string | null;
            error?: string | null;
            model?: string | null;
            probableCause?: string | null;
            /** @enum {string|null} */
            severity?: "low" | "medium" | "high" | "critical" | null;
            /** @enum {string} */
            status: "pending" | "ok" | "error";
            suggestedFix?: string | null;
            summary?: string | null;
        };
        /** Organization */
        Organization: {
            id: string;
            name: string;
            slug: string;
        };
        /**
         * AlertSettings
         * @description Per-project настройки Telegram-алертов (ADR-0013)
         */
        AlertSettings: {
            enabled: boolean;
            /** @description N событий за окно → алерт; null = правило выключено */
            frequencyThreshold?: number | null;
            frequencyWindowSeconds: number;
            onNewIssue: boolean;
            onRegression: boolean;
            telegramChatId?: string | null;
            /** @description задан ли общий TELEGRAM_BOT_TOKEN на инстансе */
            telegramConfigured: boolean;
        };
        /** Project */
        Project: {
            /** @description DSN первого активного ключа */
            dsn?: string | null;
            /** @description События за последние 24 часа (в списке проектов) */
            events24h?: number | null;
            id: string;
            name: string;
            platform?: string | null;
            slug: string;
            /** @description Счётчик unresolved issues (в списке проектов) */
            unresolvedIssues?: number | null;
        };
        /** EventList */
        EventList: components["schemas"]["Event"][];
        /** ReleaseDetail */
        ReleaseDetail: {
            /** Format: date-time */
            firstEventAt?: string | null;
            id: string;
            newIssues: components["schemas"]["Issue"][];
            ordinal: number;
            version: string;
        };
        /** SetupStatus */
        SetupStatus: {
            setupRequired: boolean;
        };
        /** ApiTokenCreateRequest */
        ApiTokenCreateRequest: {
            name: string;
        };
        /** TraceSummary */
        TraceSummary: {
            durationMs: number;
            environment?: string;
            release?: string;
            /** Format: date-time */
            startTs: string;
            status?: string;
            traceId: string;
        };
        /**
         * Trace
         * @description Спаны и ошибки трейса по всем проектам организации (ADR-0014)
         */
        Trace: {
            errors: components["schemas"]["RelatedError"][];
            spans: components["schemas"]["TraceSpan"][];
            traceId: string;
        };
        /** IssueList */
        IssueList: components["schemas"]["Issue"][];
        /** ApiToken */
        ApiToken: {
            id: string;
            /** Format: date-time */
            insertedAt: string;
            name: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** TraceSummaryList */
        TraceSummaryList: components["schemas"]["TraceSummary"][];
        /** FilterValues */
        FilterValues: {
            environments: string[];
            releases: string[];
        };
        /**
         * ApiTokenCreated
         * @description Плейнтекст `token` показывается только в этом ответе (ADR-0017)
         */
        ApiTokenCreated: {
            id: string;
            /** Format: date-time */
            insertedAt: string;
            name: string;
            /** @description swt_... */
            token: string;
        };
        /** Issue */
        Issue: {
            /** @description только в деталке; null, если анализ не запрашивался */
            aiAnalysis?: components["schemas"]["AIAnalysis"] | null;
            /** @description только в деталке: настроен ли AI на инстансе (ZAI_API_KEY) */
            aiEnabled?: boolean | null;
            /** @description times_seen */
            count: number;
            culprit: string;
            /** Format: date-time */
            firstSeen: string;
            id: string;
            /** Format: date-time */
            lastSeen: string;
            /** @enum {string} */
            level: "fatal" | "error" | "warning" | "info" | "debug";
            project?: {
                id?: string;
                slug?: string;
            } | null;
            /** @description вернулся в релизе новее закрытия */
            regressed?: boolean;
            /** @enum {string} */
            status: "unresolved" | "resolved" | "ignored";
            title: string;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Format: email */
            email: string;
            name?: string;
            /** @default Swatter */
            orgName: string;
            /** @default swatter */
            orgSlug: string;
            password: string;
        };
        /**
         * RelatedError
         * @description Ошибка того же трейса (кросс-сервисная связка, ADR-0014)
         */
        RelatedError: {
            eventId: string;
            issueId: string;
            level: string;
            projectId: string;
            projectSlug?: string | null;
            /** Format: date-time */
            timestamp: string;
            title: string;
        };
        /** IssueUpdateRequest */
        IssueUpdateRequest: {
            /** @enum {string} */
            status: "unresolved" | "resolved" | "ignored";
        };
        /** TagEntry */
        TagEntry: {
            key: string;
            value: string;
        };
        /** Release */
        Release: {
            /** Format: date-time */
            firstEventAt?: string | null;
            id: string;
            /** @description новых issues в релизе */
            newIssues?: number | null;
            /** @description порядок в проекте (больше = новее) */
            ordinal: number;
            version: string;
        };
        /** Event */
        Event: {
            /** @description breadcrumbs из исходного события */
            breadcrumbs?: unknown;
            /** @description contexts из исходного события */
            contexts?: unknown;
            /** Format: date-time */
            dateReceived?: string;
            environment?: string;
            eventId: string;
            /** @description Структура exception из исходного события (values/stacktrace/frames) */
            exception?: unknown;
            level: string;
            message?: string;
            platform?: string;
            release?: string;
            sdk?: {
                name?: string;
                version?: string;
            };
            tags?: components["schemas"]["TagEntry"][];
            /** Format: date-time */
            timestamp: string;
            traceId?: string;
            user?: {
                email?: string;
                id?: string;
                ipAddress?: string;
            };
        };
        /** ProjectUpdateRequest */
        ProjectUpdateRequest: {
            name: string;
            platform?: string | null;
        };
        /** AlertSettingsUpdateRequest */
        AlertSettingsUpdateRequest: {
            enabled?: boolean;
            frequencyThreshold?: number | null;
            frequencyWindowSeconds?: number;
            onNewIssue?: boolean;
            onRegression?: boolean;
            telegramChatId?: string | null;
        };
        /** TransactionStatList */
        TransactionStatList: components["schemas"]["TransactionStat"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "SwatterWeb.ApiTokenController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenList"];
                };
            };
        };
    };
    "SwatterWeb.ApiTokenController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Имя токена */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreateRequest"];
            };
        };
        responses: {
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            /** @description Ошибка */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ApiTokenController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отозван */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.AuthController.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Учётные данные */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Текущий пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Неверные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.AuthController.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия завершена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "SwatterWeb.AuthController.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Не аутентифицирован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.AuthController.setup_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статус */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    "SwatterWeb.AuthController.setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Данные владельца */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Созданный пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Система уже настроена */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.IssueController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.IssueController.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: number;
            };
            cookie?: never;
        };
        /** @description Новый статус */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IssueUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённый issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description Некорректный статус */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.IssueController.analyze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Анализ поставлен в очередь */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnalysis"];
                };
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description AI не настроен */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.EventController.index": {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                issue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description События */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Некорректный курсор */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Issue не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.EventController.latest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Событие */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.OrganizationController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Организации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    "SwatterWeb.ProjectController.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проекты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Организация не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ProjectController.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
            };
            cookie?: never;
        };
        /** @description Проект */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Созданный проект */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Организация не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.PerformanceController.trace": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Трейс */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            /** @description Трейс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.PerformanceController.trace_errors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ошибки трейса */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedErrorList"];
                };
            };
            /** @description Организация не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ProjectController.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        /** @description Изменения */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённый проект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ProjectController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.AlertSettingsController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSettings"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.AlertSettingsController.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        /** @description Изменения */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённые настройки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSettings"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ArtifactController.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        /** @description multipart-форма */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    debug_id: string;
                    /** Format: binary */
                    file: string;
                    name?: string;
                    /** @enum {string} */
                    type: "source_map" | "minified_source";
                };
            };
        };
        responses: {
            /** @description Загружено */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Некорректная форма */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.IssueController.filters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Значения фильтров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterValues"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.IssueController.index": {
        parameters: {
            query?: {
                status?: "unresolved" | "resolved" | "ignored" | "all";
                sort?: "date" | "new" | "freq";
                /** @description Поиск по заголовку и culprit */
                query?: string;
                /** @description Фильтр по окружению событий */
                environment?: string;
                /** @description Фильтр по релизу событий */
                release?: string;
                /** @description Из Link-заголовка прошлого ответа */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueList"];
                };
            };
            /** @description Некорректный курсор */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.PerformanceController.traces": {
        parameters: {
            query: {
                transaction: string;
                window?: "1h" | "24h" | "7d";
                sort?: "slow" | "recent";
            };
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Трейсы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummaryList"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.PerformanceController.transactions": {
        parameters: {
            query?: {
                window?: "1h" | "24h" | "7d";
            };
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Транзакции */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionStatList"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ReleaseController.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Релизы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "SwatterWeb.ReleaseController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_slug: string;
                project_slug: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Релиз с новыми issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
