import Config

# Configure your database
config :swatter, Swatter.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  # 5433 — хост-порт postgres из compose.yaml (нестандартный, см. комментарий там)
  port: String.to_integer(System.get_env("PGPORT") || "5433"),
  database: "swatter_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# 6380 — хост-порт redis из compose.yaml (нестандартный, см. комментарий там)
config :swatter, :redis_url, "redis://localhost:#{System.get_env("REDIS_PORT") || "6380"}"

# ClickHouse из compose.yaml (пользователь swatter/swatter, HTTP-порт 8123)
config :swatter, Swatter.EventsRepo,
  url:
    "http://swatter:swatter@localhost:#{System.get_env("CLICKHOUSE_PORT") || "8123"}/swatter_dev"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :swatter, SwatterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "r4I41UT+3sPtCmOLPE/veLVApYplFh69RcnTW0tvkY91Dx0WZTE7HRYQnN9MCua9",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :swatter, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
